### ISSUE TITLE
ORDS 404 Error

### ISSUE THREAD

**Issue by jhmk** [araczkowski/docker-oracle-apex-ords#12]
Have this error two times now after a specific time when the docker was running for about 7 days.
On http://IP:49161/ords/ it shows a 404 Error.

`URLMappingNotFoundException [statusCode=404, reasons=[The request could not be mapped to any database. Check the request URL is correct, and that URL to database mappings have been correctly configured]]
	at oracle.dbtools.url.mapping.filter.URLMappingFilter.doFilter(URLMappingFilter.java:119)
	at oracle.dbtools.http.filters.HttpFilter.doFilter(HttpFilter.java:47)
	at oracle.dbtools.http.filters.FilterChainImpl.doFilter(FilterChainImpl.java:64)
	at oracle.dbtools.http.cors.CORSResponseFilter.doFilter(CORSResponseFilter.java:83)
	at oracle.dbtools.http.filters.HttpResponseFilter.doFilter(HttpResponseFilter.java:45)
	at oracle.dbtools.http.filters.FilterChainImpl.doFilter(FilterChainImpl.java:64)
	at oracle.dbtools.http.errors.ErrorPageFilter.doFilter(ErrorPageFilter.java:94)
	at oracle.dbtools.http.filters.HttpFilter.doFilter(HttpFilter.java:47)
	at oracle.dbtools.http.filters.FilterChainImpl.doFilter(FilterChainImpl.java:64)
	at oracle.dbtools.http.auth.ForceAuthFilter.doFilter(ForceAuthFilter.java:44)
	at oracle.dbtools.http.filters.HttpFilter.doFilter(HttpFilter.java:47)
	at oracle.dbtools.http.filters.FilterChainImpl.doFilter(FilterChainImpl.java:64)
	at oracle.dbtools.http.filters.Filters.filter(Filters.java:47)
	at oracle.dbtools.http.entrypoint.EntryPoint.service(EntryPoint.java:82)
	at oracle.dbtools.http.entrypoint.EntryPointServlet.service(EntryPointServlet.java:49)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:725)
	at oracle.dbtools.rt.web.HttpEndpointBase.dispatchableServices(HttpEndpointBase.java:116)
	at oracle.dbtools.rt.web.HttpEndpointBase.service(HttpEndpointBase.java:81)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:725)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:504)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:610)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:534)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1081)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:658)
	at org.apache.coyote.http11.Http11NioProtocol$Http11ConnectionHandler.process(Http11NioProtocol.java:222)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1566)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1523)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Unknown Source)`

**Comment by jhmk** [comment]
Turns out ORDS have a setting that the Admin Password will be reseted after x days.
